package com.husc.lms.enums;

public enum NotificationType {
	COMMENT,
	MESSAGE,
	COMMENT_REPLY,
	CHAT_MESSAGE,
	JOIN_CLASS_PENDING,
	JOIN_CLASS_REJECTED,
	JOIN_CLASS_APPROVED,
	POST_CREATED,
	POST_COMMENT,
	POST_COMMENT_REPLY
}
